[server]
follow_symlink = false
browser = "default"

[save]
autosave_delay = 1000
autosave = "off"
format_on_save = true

[runtime]
output_max_bytes = 8000000
reactive_tests = true
std_stream_max_bytes = 1000000
on_cell_change = "autorun"
auto_reload = "off"
default_sql_output = "auto"
watcher_on_save = "lazy"
auto_instantiate = false
default_auto_download = ["ipynb"]

[datasources]

[completion]
copilot = "github"
activate_on_typing = true

[ai]
rules = ""
inline_tooltip = false
mode = "manual"

[ai.models]
custom_models = []
displayed_models = []

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[mcp]
presets = []

[mcp.mcpServers]

[diagnostics]
sql_linter = true

[package_management]
manager = "uv"

[experimental]

[language_servers.ty]

[language_servers.basedpyright]

[language_servers.pylsp]
enable_mypy = true
enable_pylint = false
enable_pyflakes = false
enabled = true
enable_pydocstyle = false
enable_flake8 = false
enable_ruff = true

[formatting]
line_length = 79

[snippets]
include_default_snippets = true
custom_paths = []

[display]
default_width = "medium"
default_table_page_size = 10
reference_highlighting = false
code_editor_font_size = 16
default_table_max_columns = 50
theme = "light"
dataframes = "rich"
cell_output = "below"
